[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[scheduled.functions]]
  name = "ingest-episodes-background"
  cron = "*/30 * * * *"

[[scheduled.functions]]
  name = "summarize-episodes-background"
  cron = "20,50 * * * *"
